services:
  
  app:
    build: ./app
    links:
      - db
    ports:
      - 8000:8000
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - 32000:3306
