#!/bin/python

class Laptop:
    def __init__(self):
        display = Component(
            "Display is showing you information generated by OS.")
        os = Component(
            "OS is one of the most important components that will bring you a great functionality.")
        cpu = Component(
            "It's the most needed part to make all components work as a single - CPU.")
        memory = Component("Memory is a brain of a computer.")
        keyboard = Component(
            "Keyboard is an interface by which you can interact with your computer.")
        self.components = [display, os, cpu, memory, keyboard]

    def show_components(self):
        for component in self.components:
            print(component.description)


class Component:
    def __init__(self, description):
        self.description = description


# If you destroy Laptop instance then any instances of Component are destroyed too
myLaptop = Laptop()
myLaptop.show_components()
